export const FETCH_WORKOUT_VALUES = "FETCH_WORKOUT_VALUES";
export const FETCH_OPPONENT_VALUES = "FETCH_OPPONENT_VALUES";
export const FETCH_WORKOUT_USER = "FETCH_WORKOUT_USER";
export const FETCH_USERS_LOGIN = "FETCH_USERS_LOGIN";
